export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS'
export const HANDLE_ERROR = 'HANDLE_ERROR'

export const PURCHASE_BURER_START = 'PURCHASE_BURER_START'
export const PURCHASE_BURER_SUCCESS = 'PURCHASE_BURER_SUCCESS'
export const PURCHASE_BURER_FAIL = 'PURCHASE_BURER_FAIL'
export const PURCHASE_INIT = 'PURCHASE_INIT'

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const TOGGLE_SIDEDRAWER = 'TOGGLE_SIDEDRAWER'
